title: Luc Doucette
logo: assets/img/IMG_20210815_174950_407.jpg
# description
Description: Linkedin: https://www.linkedin.com/in/lucdoucette/ Email: lucadoucette@gmail.com
# show_downloads: true
theme: jekyll-theme-minimal
