# Site Settings
title: Luc Doucette
logo: assets/img/IMG_20210815_174950_407.jpg
description: "This is my personal website, showcasing my projects and experience."
show_downloads: true

# Social links
author:
  email: lucadoucette@gmail.com
  github_username: l-doucette
  linkedin_username: lucdoucette
  
# Theme
theme: jekyll-theme-minimal
