# Site Settings
title: Luc Doucette
logo: assets/img/IMG_20210815_174950_407.jpg
email: lucadoucette@gmail.com
description: "This is my personal website, showcasing my projects and experience."
show_downloads: true

# Social links
social_links:
  linkedin: "https://www.linkedin.com/in/lucdoucette/"
  email: "mailto:lucadoucette@gmail.com" 
  
# Theme
theme: jekyll-theme-minimal
